version: 1.0.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: VS15
    - PlatformToolset: VS17

platform:
    - x64
    - Any CPU

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Any CPU" set archi=x86
    - if "%platform%"=="Any CPU" set platform_input=Any CPU

    - if "%PlatformToolset%"=="VS15" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="VS17" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

    #build needs the libs from RegExTractor, so download and place them at the right folder
    - md "%APPVEYOR_BUILD_FOLDER%"\src\NppRegExTractor\RegExTractor
    - cd "%APPVEYOR_BUILD_FOLDER%"\src\NppRegExTractor\RegExTractor
    - appveyor DownloadFile https://github.com/viper3400/RegExTractor/releases/download/1.3.4/RegExTractor_V1.3.4.zip
    - 7z e RegExTractor_V1.3.4.zip -y

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\src
    - msbuild NppRegExTractor.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%"  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\src\NppRegExTractor
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppRegExTractorPlugin.dll" -FileName NppRegExTractorPlugin.dll
        }

        if ($env:PLATFORM_INPUT -eq "Any CPU" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:CONFIGURATION\NppRegExTractorPlugin.dll" -FileName NppRegExTractorPlugin.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "VS17") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "NppRegExTractor_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppRegExTractorPlugin.dll
            }
            if($env:PLATFORM_INPUT -eq "Any CPU"){
            $ZipFileName = "NppRegExTractor_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName bin\$env:CONFIGURATION\NppRegExTractorPlugin.dll
            }
        }

artifacts:
  - path: NppRegExTractor_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: VS17
        configuration: Release
